name: CI

on:
  push:

jobs:
  build:
    strategy:
      # The matrix will run all possible combinations in parallel.
      matrix:
        container: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      # Use Go 1.17
      - name: Switch to Go 1.17
        run:
          echo "$GOROOT_1_17_X64"/bin >> $GITHUB_PATH

      - name: Go dependencies
        shell: bash
        run: |
          make go_dependencies
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Toit dependencies
        id: toit
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            curl -O -L https://github.com/toitlang/toit/releases/download/v0.14.0/toit-linux.tar.gz
            tar x -f toit-linux.tar.gz
            echo "::set-output name=toitvm::$PWD/toit/bin/toit.run"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            curl -O -L https://github.com/toitlang/toit/releases/download/v0.14.0/toit-macos.tar.gz
            tar x -f toit-macos.tar.gz
            echo "::set-output name=toitvm::$PWD/toit/bin/toit.run"
          else
            echo "UNSUPPORTED RUNNER: $RUNNER_OS"
            exit 1
          fi

      - name: Build
        run: |
          make

      # Test.
      - name: test
        env:
          TOITPKG_PATH: ${{ github.workspace }}/build/toitpkg
          TOITVM_PATH: ${{ steps.toit.outputs.toitvm }}
        run: |
          make test
