name: CI

on:
  push:

jobs:
  build:
    strategy:
      # The matrix will run all possible combinations in parallel.
      matrix:
        container: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up constants
        shell: bash
        id: constants
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            echo toit_archive=toit-linux.tar.gz >> $GITHUB_OUTPUT
            echo 'toitvm=${{ github.workspace }}/toit/bin/toit.run' >> $GITHUB_OUTPUT
            echo 'toitpkg=${{ github.workspace }}/build/toitpkg' >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "macOS" ]; then
            echo toit_archive=toit-macos.tar.gz >> $GITHUB_OUTPUT
            echo 'toitvm=${{ github.workspace }}/toit/bin/toit.run' >> $GITHUB_OUTPUT
            echo 'toitpkg=${{ github.workspace }}/build/toitpkg' >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo toit_archive=toit-windows.tar.gz >> $GITHUB_OUTPUT
            echo 'toitvm=${{ github.workspace }}\toit\bin\toit.run.exe' >> $GITHUB_OUTPUT
            echo 'toitpkg=${{ github.workspace }}\build\toitpkg.exe' >> $GITHUB_OUTPUT
          else
            echo "UNSUPPORTED RUNNER: $RUNNER_OS"
            exit 1
          fi

      # Use Go 1.20
      - name: Switch to Go 1.20
        uses: actions/setup-go@v5
        with:
          go-version: 1.20

      - name: Go dependencies
        shell: bash
        run: |
          make go_dependencies
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Toit dependencies
        id: toit
        shell: bash
        run: |
          curl -O -L https://github.com/toitlang/toit/releases/download/v2.0.0-alpha.95/${{ steps.constants.outputs.toit_archive }}
          tar x -f ${{ steps.constants.outputs.toit_archive }}

      - name: Build
        run: |
          make

      # Test.
      - name: test
        env:
          TOITPKG_PATH: ${{ steps.constants.outputs.toitpkg }}
          TOITVM_PATH: ${{ steps.constants.outputs.toitvm }}
        run: |
          make test
